### PR TITLE
Noko renaming

### PR DESCRIPTION
**Pull request by tcannonfodder**

### CODE REVIEW

**Comment by timcraft** [comment]
If you're changing the endpoints could I suggest an alternative to invoiced_outside_of_noko:

* PUT /v2/entries/:id/invoice_date
* PUT /v2/entries/invoice_date

(Or invoiced_at if you'd rather match the attribute name.)

**Comment by tcannonfodder** [comment]
@timcraft That's a really good idea! I'm going to merge the API docs as-is (and we'll support `invoiced_outside_of_noko` to make it easier for developers that are updating their API clients with a find/replace pass), but I'm making a new issue for this. :)

**Comment by timcraft** [comment]
@tcannonfodder Great, thanks! New hostname seems to be working ok.

Using a `X-NokoToken` header isn't working though, has that been updated yet?

**Comment by tcannonfodder** [comment]
@timcraft  Sorry about that! It should work now; just deployed a bugfix!

**Pull request merged**
